name: mir-kiosk-chromium
summary: Chromium web browser in Kiosk mode on Mir
description: |
 An open-source browser project that aims to build a safer, faster, and more
 stable way for all Internet users to experience the web.
adopt-info: ppa-build
confinement: strict
grade: stable

apps:
  chromium-mir-kiosk:
    command: desktop-launch xwayland-kiosk-launch chromium-browser.launcher --no-sandbox
    daemon: simple
    desktop: usr/share/applications/chromium.desktop
    environment:
      CHROME_DESKTOP: chromium.desktop
      XWAYLAND_I3_CONFIG_FILE: $SNAP/etc/i3.config
    slots: [ x11 ]
    plugs:
      - browser-sandbox
      - camera
      - cups-control
      - desktop
      - gsettings
      - hardware-observe
      - home
      - mount-observe
      - network
      - network-manager
      - opengl
      - password-manager-service
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - wayland
      - x11-plug

plugs:
  browser-support:
    allow-sandbox: false
  x11-plug: # because cannot have identical plug/slot name in same yaml.
    interface: x11

parts:
  ppa-build:
    plugin: nil
    build-packages:
      - software-properties-common
    stage-packages:
      - libgl1-mesa-glx
      - libgnome-keyring0
      - libnss3
      - pulseaudio
    #      add-apt-repository --yes --update ppa:chromium-team/stable
    override-build: |
      apt install software-properties-common
      snapcraftctl set-version "$(env LANG=C apt-cache policy chromium-browser | sed -rne 's/^\s+Candidate:\s+(.*)-[^-]+$/\1/p')"
      apt install -y chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib
      cp -R /usr/lib/chromium-browser $SNAPCRAFT_PART_INSTALL/usr/lib/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp /usr/bin/chromium-browser $SNAPCRAFT_PART_INSTALL/usr/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc
      cp -R /etc/chromium-browser $SNAPCRAFT_PART_INSTALL/etc/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      cp /usr/share/icons/hicolor/256x256/apps/chromium-browser.png \
          $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/chromium.png
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cp /usr/share/applications/chromium-browser.desktop \
          $SNAPCRAFT_PART_INSTALL/usr/share/applications/chromium.desktop
      sed -i \
          -e "s:^Exec=chromium-browser\(.*\):Exec=chromium\1:g" \
          -e "s:^Icon=chromium-browser$:Icon=/usr/share/icons/hicolor/256x256/apps/chromium.png:" \
          $SNAPCRAFT_PART_INSTALL/usr/share/applications/chromium.desktop
      chmod 4555 $SNAPCRAFT_PART_INSTALL/usr/lib/chromium-browser/chrome-sandbox

  kiosk-extension:
    plugin: nil
    source: https://git.launchpad.net/~gerboland/+git/chromium-kiosk-app-snap
    source-type: git
    stage-packages: [ jq ] # ease using JSON in Bash
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/chromium-browser/kiosk-app
      cp -R * $SNAPCRAFT_PART_INSTALL/etc/chromium-browser/kiosk-app
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/chromium-browser/policies/managed/
      cp ../../../glue/chromium-policy.json $SNAPCRAFT_PART_INSTALL/etc/chromium-browser/policies/managed/
  desktop-gtk3:
    build-packages:
      - build-essential
      - libgtk-3-dev
    make-parameters:
      - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3
  launcher:
    plugin: dump
    source: glue
    after: [desktop-gtk3, xwayland-kiosk-helper]
    organize:
      chromium-browser.launcher: bin/
      i3.config: etc/
base: core18
